apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdfnhsfnhfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdfnhsfnhfs
  template:
    metadata:
      labels:
        app: sdfnhsfnhfs
    spec:
      containers:
        - name: sdfnhsfnhfs-server
          image: ghcr.io/apisitssi/sdfnhsfnhfs
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sdfnhsfnhfs-service
  labels:
    app: sdfnhsfnhfs-service
spec:
  selector:
    app: sdfnhsfnhfs
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP