apiVersion: apps/v1
kind: Deployment
metadata:
  name: user07
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user07
  template:
    metadata:
      labels:
        app: user07
    spec:
      containers:
        - name: user07-server
          image: ghcr.io/apisitssi/sdfnhsfnhfs
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: user07-service
  labels:
    app: user07-service
spec:
  selector:
    app: user07
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP